[package]
name = "mini_db"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

rustyline = "17"
serde_json = "1.0"

clap = { version = "4", features = ["derive"] }
prettytable = "0.10"
