[package]
name = "mini_db"
version = "0.1.0"
edition = "2024"

[dependencies]
prettytable = "0.10"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
